Test CI
mozilla-b2g/gaia pull request #25530
Opened 2014-10-27 09:26 UTC by evanxd

2015-01-06 03:08 UTC, try-server-hook commented
[<img src="https://avatars.githubusercontent.com/u/3013038?v=3" alt="evanxd" width="50px" height="50px" /> Evan Tseng (evanxd)](https://github.com/evanxd) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=efc409ba98d2)

2015-01-07 03:35 UTC, try-server-hook commented
[<img src="https://avatars.githubusercontent.com/u/3013038?v=3" alt="evanxd" width="50px" height="50px" /> Evan Tseng (evanxd)](https://github.com/evanxd) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=720f46597770)

2015-01-12 03:15 UTC, try-server-hook commented
[<img src="https://avatars.githubusercontent.com/u/3013038?v=3" alt="evanxd" width="50px" height="50px" /> Evan Tseng (evanxd)](https://github.com/evanxd) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=4b192caad25a)

2015-01-13 02:52 UTC, try-server-hook commented
[<img src="https://avatars.githubusercontent.com/u/3013038?v=3" alt="evanxd" width="50px" height="50px" /> Evan Tseng (evanxd)](https://github.com/evanxd) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=5b6cbbdc3da9)

2015-01-15 03:51 UTC, try-server-hook commented
[<img src="https://avatars.githubusercontent.com/u/3013038?v=3" alt="evanxd" width="50px" height="50px" /> Evan Tseng (evanxd)](https://github.com/evanxd) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=63c3a87384fb)

2015-01-16 08:23 UTC, try-server-hook commented
[<img src="https://avatars.githubusercontent.com/u/3013038?v=3" alt="evanxd" width="50px" height="50px" /> Evan Tseng (evanxd)](https://github.com/evanxd) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=a67e8d65b51d)

2015-01-20 03:26 UTC, try-server-hook commented
[<img src="https://avatars.githubusercontent.com/u/3013038?v=3" alt="evanxd" width="50px" height="50px" /> Evan Tseng (evanxd)](https://github.com/evanxd) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=05c0ba3034d4)

2015-01-21 03:15 UTC, try-server-hook commented
[<img src="https://avatars.githubusercontent.com/u/3013038?v=3" alt="evanxd" width="50px" height="50px" /> Evan Tseng (evanxd)](https://github.com/evanxd) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=060e2e67627e)

2015-01-22 03:11 UTC, try-server-hook commented
[<img src="https://avatars.githubusercontent.com/u/3013038?v=3" alt="evanxd" width="50px" height="50px" /> Evan Tseng (evanxd)](https://github.com/evanxd) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=f3b18c925adf)

2015-01-25 03:26 UTC, try-server-hook commented
[<img src="https://avatars.githubusercontent.com/u/3013038?v=3" alt="evanxd" width="50px" height="50px" /> Evan Tseng (evanxd)](https://github.com/evanxd) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=4330be454c77)

2015-01-26 03:11 UTC, try-server-hook commented
[<img src="https://avatars.githubusercontent.com/u/3013038?v=3" alt="evanxd" width="50px" height="50px" /> Evan Tseng (evanxd)](https://github.com/evanxd) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=9b36715ae176)

2015-01-27 03:22 UTC, try-server-hook commented
[<img src="https://avatars.githubusercontent.com/u/3013038?v=3" alt="evanxd" width="50px" height="50px" /> Evan Tseng (evanxd)](https://github.com/evanxd) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=5ddc1994e145)

2015-01-28 03:44 UTC, try-server-hook commented
[<img src="https://avatars.githubusercontent.com/u/3013038?v=3" alt="evanxd" width="50px" height="50px" /> Evan Tseng (evanxd)](https://github.com/evanxd) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=d8765e48a9f1)

2015-01-29 03:20 UTC, try-server-hook commented
[<img src="https://avatars.githubusercontent.com/u/3013038?v=3" alt="evanxd" width="50px" height="50px" /> Evan Tseng (evanxd)](https://github.com/evanxd) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=38cd75ce1daf)

2015-01-30 02:37 UTC, try-server-hook commented
[<img src="https://avatars.githubusercontent.com/u/3013038?v=3" alt="evanxd" width="50px" height="50px" /> Evan Tseng (evanxd)](https://github.com/evanxd) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=566b686e4c95)

2015-02-03 03:06 UTC, autolander commented
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

2015-02-03 03:07 UTC, try-server-hook commented
[<img src="https://avatars.githubusercontent.com/u/3013038?v=3" alt="evanxd" width="50px" height="50px" /> Evan Tseng (evanxd)](https://github.com/evanxd) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=7f1b5abda00a)

2015-02-04 03:42 UTC, autolander commented
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

2015-02-04 03:43 UTC, try-server-hook commented
[<img src="https://avatars.githubusercontent.com/u/3013038?v=3" alt="evanxd" width="50px" height="50px" /> Evan Tseng (evanxd)](https://github.com/evanxd) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=d966f6a749eb)

2015-02-05 03:05 UTC, autolander commented
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

2015-02-05 03:06 UTC, try-server-hook commented
[<img src="https://avatars.githubusercontent.com/u/3013038?v=3" alt="evanxd" width="50px" height="50px" /> Evan Tseng (evanxd)](https://github.com/evanxd) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=5d125cfdac2a)

2015-02-06 02:51 UTC, autolander commented
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

2015-02-06 02:52 UTC, try-server-hook commented
[<img src="https://avatars.githubusercontent.com/u/3013038?v=3" alt="evanxd" width="50px" height="50px" /> Evan Tseng (evanxd)](https://github.com/evanxd) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=d1c3d86414c3)

2015-02-09 03:22 UTC, autolander commented
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

2015-02-09 03:23 UTC, try-server-hook commented
[<img src="https://avatars.githubusercontent.com/u/3013038?v=3" alt="evanxd" width="50px" height="50px" /> Evan Tseng (evanxd)](https://github.com/evanxd) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=f879ae97e78c)

2015-02-10 03:10 UTC, autolander commented
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

2015-02-10 03:11 UTC, try-server-hook commented
[<img src="https://avatars.githubusercontent.com/u/3013038?v=3" alt="evanxd" width="50px" height="50px" /> Evan Tseng (evanxd)](https://github.com/evanxd) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=b8be5be5cc2d)

2015-02-12 03:32 UTC, autolander commented
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

2015-02-12 03:33 UTC, try-server-hook commented
[<img src="https://avatars.githubusercontent.com/u/3013038?v=3" alt="evanxd" width="50px" height="50px" /> Evan Tseng (evanxd)](https://github.com/evanxd) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=e1335fe59f25)

2015-02-13 03:17 UTC, autolander commented
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

2015-02-13 03:18 UTC, try-server-hook commented
[<img src="https://avatars.githubusercontent.com/u/3013038?v=3" alt="evanxd" width="50px" height="50px" /> Evan Tseng (evanxd)](https://github.com/evanxd) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=5be52de9b814)

2015-02-16 03:39 UTC, autolander commented
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

2015-02-16 03:40 UTC, try-server-hook commented
[<img src="https://avatars.githubusercontent.com/u/3013038?v=3" alt="evanxd" width="50px" height="50px" /> Evan Tseng (evanxd)](https://github.com/evanxd) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=f1d9291a3ac8)

2015-02-17 03:36 UTC, autolander commented
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

2015-02-17 03:37 UTC, try-server-hook commented
[<img src="https://avatars.githubusercontent.com/u/3013038?v=3" alt="evanxd" width="50px" height="50px" /> Evan Tseng (evanxd)](https://github.com/evanxd) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=a9222a713c05)

2015-02-24 02:32 UTC, autolander commented
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

2015-02-24 02:32 UTC, try-server-hook commented
[<img src="https://avatars.githubusercontent.com/u/3013038?v=3" alt="evanxd" width="50px" height="50px" /> Evan Tseng (evanxd)](https://github.com/evanxd) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=0e9f5721b479)

2015-02-25 03:05 UTC, autolander commented
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

2015-02-25 03:06 UTC, try-server-hook commented
[<img src="https://avatars.githubusercontent.com/u/3013038?v=3" alt="evanxd" width="50px" height="50px" /> Evan Tseng (evanxd)](https://github.com/evanxd) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=e4733045118d)

2015-02-26 03:06 UTC, autolander commented
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

2015-02-26 03:07 UTC, try-server-hook commented
[<img src="https://avatars.githubusercontent.com/u/3013038?v=3" alt="evanxd" width="50px" height="50px" /> Evan Tseng (evanxd)](https://github.com/evanxd) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=56b3d3db97d7)

2015-03-03 00:29 UTC, autolander commented
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

2015-03-03 00:30 UTC, try-server-hook commented
[<img src="https://avatars.githubusercontent.com/u/3013038?v=3" alt="evanxd" width="50px" height="50px" /> Evan Tseng (evanxd)](https://github.com/evanxd) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=2eeacfabbcb5)

2015-03-04 02:29 UTC, autolander commented
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

2015-03-04 02:30 UTC, try-server-hook commented
[<img src="https://avatars.githubusercontent.com/u/3013038?v=3" alt="evanxd" width="50px" height="50px" /> Evan Tseng (evanxd)](https://github.com/evanxd) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=f833fb0408e7)

2015-03-05 03:13 UTC, autolander commented
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

2015-03-05 03:15 UTC, try-server-hook commented
[<img src="https://avatars.githubusercontent.com/u/3013038?v=3" alt="evanxd" width="50px" height="50px" /> Evan Tseng (evanxd)](https://github.com/evanxd) started tests. [Results](https://treeherder.mozilla.org/ui/#/jobs?repo=gaia-try&revision=95b2777ca41a)

2018-02-14 11:57 UTC, ranglaly requested changes

2018-02-14 11:57 UTC, ranglaly commented on README.md
>  # Gaia [![Build Status](https://travis-ci.org/mozilla-b2g/gaia.svg)](https://travis-ci.org/mozilla-b2g/gaia)
(fire fox )send data to kai os (jiophone) apps


ajgmgptj5.6gpt78pg1 '&4j

2021-11-03 13:04 UTC, closed without merging